#version 450
layout(local_size_x = 8, local_size_y = 8, local_size_z = 1) in;

layout(set = 0, binding = 0) uniform samplerCube environmentMap;
layout(set = 0, binding = 1, rgba32f) uniform writeonly image2DArray irradianceMap;

const float PI = 3.14159265359;

vec3 getDir(uint face, vec2 uv) {
    vec3 dir;
    if      (face == 0) dir = vec3( 1.0, -uv.y, -uv.x); // +X
    else if (face == 1) dir = vec3(-1.0, -uv.y,  uv.x); // -X
    else if (face == 2) dir = vec3( uv.x,  1.0,  uv.y); // +Y
    else if (face == 3) dir = vec3( uv.x, -1.0, -uv.y); // -Y
    else if (face == 4) dir = vec3( uv.x, -uv.y,  1.0); // +Z
    else if (face == 5) dir = vec3(-uv.x, -uv.y, -1.0); // -Z
    return normalize(dir);
}

void main() {
    ivec3 pos = ivec3(gl_GlobalInvocationID);
    ivec2 size = imageSize(irradianceMap).xy;
    if (pos.x >= size.x || pos.y >= size.y) return;

    vec2 uv = (vec2(pos.xy) + 0.5) / vec2(size);
    uv = uv * 2.0 - 1.0;
    vec3 N = getDir(pos.z, uv);

    vec3 irradiance = vec3(0.0);
    vec3 up    = vec3(0.0, 1.0, 0.0);
    vec3 right = normalize(cross(up, N));
    up         = normalize(cross(N, right));

    // Reduced delta for cinematic smooth diffuse
    float sampleDelta = 0.005;
    float nrSamples = 0.0;

    for(float phi = 0.0; phi < 2.0 * PI; phi += sampleDelta) {
        for(float theta = 0.0; theta < 0.5 * PI; theta += sampleDelta) {
            vec3 tangentSample = vec3(sin(theta) * cos(phi),  sin(theta) * sin(phi), cos(theta));
            vec3 sampleVec = tangentSample.x * right + tangentSample.y * up + tangentSample.z * N;
            irradiance += texture(environmentMap, sampleVec).rgb * cos(theta) * sin(theta);
            nrSamples++;
        }
    }
    irradiance = PI * irradiance * (1.0 / float(nrSamples));
    imageStore(irradianceMap, pos, vec4(irradiance, 1.0));
}
